#### Step 1: Check if library name 'numpy' is installed or not?

In [3]:
pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: d:\Document\Programer\Python Training\Projects\Python_testing\env\Lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


#### Step 2: Install Numpy

In [2]:
pip install numpy

                                              0.0/15.5 MB ? eta -:--:--
                                              0.3/15.5 MB 6.0 MB/s eta 0:00:03
     -                                        0.6/15.5 MB 6.5 MB/s eta 0:00:03
     --                                       1.1/15.5 MB 8.4 MB/s eta 0:00:02
     ----                                     1.6/15.5 MB 9.1 MB/s eta 0:00:02
     -----                                    2.1/15.5 MB 9.7 MB/s eta 0:00:02
     -------                                  2.9/15.5 MB 11.4 MB/s eta 0:00:02
     ---------                                3.6/15.5 MB 12.2 MB/s eta 0:00:01
     ----------                               4.0/15.5 MB 11.7 MB/s eta 0:00:01
     ----------                               4.1/15.5 MB 11.0 MB/s eta 0:00:02
     -----------                              4.3/15.5 MB 9.8 MB/s eta 0:00:02
     -----------                              4.5/15.5 MB 9.5 MB/s eta 0:00:02
     -----------                              4.6/15.5 


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


#### Step 3: Create array in Numpy

In [16]:
import numpy as np

a = np.array(10)                                        # scalar array 1 row & 3 column
print(a)

row = np.array([1, 2, 3])                               # vector array 1 row & 3 column
print(row)

mat = np.array([[1, 2, 3],[2, 2, 3], [3, 2, 3]])        # matrix array: 3 row & 3 column
print(mat)



10
[1 2 3]
[[1 2 3]
 [2 2 3]
 [3 2 3]]


#### Step 4: Create random

In [60]:
r1 = np.random.random(5)                    # random 5 dimension
r2 = np.random.random([2, 3])               # random matrix 2 x 3
print(r1)
print(r2)

r3 = np.random.randint(0, 11, 6)            # random int from 0 to >11, 6 dimension
r4 = np.random.randint(0, 11, [2, 3])       # random int from 0 to >11, 2 x 3 dimension
print(r3)
print(r4)

[0.57997923 0.24706368 0.43897895 0.63151259 0.90002764]
[[0.95294622 0.50916994 0.73394267]
 [0.35277626 0.21190684 0.49561748]]
[1 1 3 0 1 1]
[[ 3  5 10]
 [ 2  4  9]]


#### Step 5: Access and Selected array

In [70]:
vrow = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vrow[3])          # select index
print(vrow[2:7])        # select by range from and to index
print(vrow[-1])         # select reversal index
print(vrow[:4])         # select by range from begin to index
print(vrow[-4:])        # select by range from reversal index to last

4
[3 4 5 6 7]
10
[1 2 3 4]
[ 7  8  9 10]


#### Step 6: Find Statistic value with Numpy

In [80]:
stat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(stat)

print('Max is', np.max(stat));     # find max value
print('Min is', np.min(stat));     # find min value
print('Average is', np.mean(stat));     # find average value
print('Median is', np.median(stat));     # find median value
print('Standard is', np.std(stat));     # find standard value
print('Variant is', np.var(stat));     # find variant value

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max is 12
Min is 1
Average is 6.5
Median is 6.5
Standard is 3.452052529534663
Variant is 11.916666666666666
